### Create Blog
POST http://localhost:8080/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJ1c2VybmFtZSI6InRlc3QyIiwiZXhwIjoxNzY0NjA2MzYxfQ.dsVfyv3m6JbKPdmuFQSCfyFMBkmpGAxUwTJAzRU3faY

{
    "title": "Test Blog",
    "content": "This is a test blog"
}

### Get Blog
GET http://localhost:8080/blogs/5

### Delete Blog
DELETE http://localhost:8080/blogs/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJ1c2VybmFtZSI6InRlc3QyIiwiZXhwIjoxNzY0NjA2MzYxfQ.dsVfyv3m6JbKPdmuFQSCfyFMBkmpGAxUwTJAzRU3faY

### List Blogs
GET http://localhost:8080/blogs/