###
GET http://localhost:8080/health

### Create User
POST http://localhost:8080/users/register
Content-Type: application/json

{
    "username": "test123",
    "email": "test123@test.com",
    "password": "test1234"
}

### Login User
POST http://localhost:8080/users/login
Content-Type: application/json

{
    "email": "test123@test.com",
    "password": "test1234"
}

### Get User Profile
GET http://localhost:8080/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJ1c2VybmFtZSI6InRlc3QxMjMiLCJleHAiOjE3NjMwNTAzMzh9.gvkciYh3E3g_BrnGtqB2UdIhxGS0EpDhTFb3o8uf8jk
