###
GET http://localhost:8080/health

### Create User
POST http://localhost:8080/users/register
Content-Type: application/json

{
    "username": "test",
    "email": "test@test.com",
    "password": "test1234"
}

### Login User
POST http://localhost:8080/users/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test1234"
}

### Get User Profile
GET http://localhost:8080/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InRlc3QiLCJleHAiOjE3NjQ1NTcyMTV9.ojnoVuqysjjKpAnSBKqW2LDZ9VZYw9rdnSVJQHYdt6I

### Logout User
POST http://localhost:8080/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InRlc3QxMjMiLCJleHAiOjE3NjMyMjUzNTJ9.Tz1miWfo3bRpcQqKd7ogLcHUsG38hCFYA-ixb4mY5_E

### List All Users
GET http://localhost:8080/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InRlc3QxMjMiLCJleHAiOjE3NjMyMjUzNTJ9.Tz1miWfo3bRpcQqKd7ogLcHUsG38hCFYA-ixb4mY5_E
